# privileged is necesssary to make electron app works
# https://stackoverflow.com/questions/73092750/how-to-show-gui-apps-from-docker-desktop-container-on-windows-11
# this command on windows works (docker desktop must be running)
# docker run -ti --rm --privileged -v /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix -e DISPLAY=:0 yade
# this command on linux works
# docker run -ti --rm -e DISPLAY=$DISPLAY --privileged -v /tmp/.X11-unix/:/tmp/.X11-unix/ yade

FROM coqorg/coq

# installing vscode 
RUN sudo apt-get update || true
RUN sudo apt-get install -y gnupg
RUN curl -L "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64" --output code.deb
RUN sudo apt install -y ./code.deb

# installing coq-lsp and hiearchy builder
RUN opam update
RUN opam install -y coq-lsp coq-hierarchy-builder

# Installing coreact-yade
RUN curl  -L "https://github.com/amblafont/graph-editor-web/releases/download/v0.5-alpha/coreact-yade_1.1.0_amd64.deb" --output yade.deb
RUN sudo apt-get update
RUN sudo apt install -y ./yade.deb
RUN DONT_PROMPT_WSL_INSTALL=No_Prompt_please code --install-extension amblafont.coreact-yade

# Downloading the example directory
RUN git clone https://github.com/amblafont/vscode-yade-example.git
RUN cd vscode-yade-example && make

# running the image launches vscode
CMD cd vscode-yade-example && \
    DONT_PROMPT_WSL_INSTALL=No_Prompt_please code --disable-workspace-trust example.v \
    && echo "Press RET to finish" && read

